env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Package everything
      run: |
        mkdir release
        cp -r . release/
        rm -rf release/.git release/.github
        zip -r release.zip release/

    - name: Upload full package
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: release.zip
        
