env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

name: C/C++ CI + Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Package source + binary
      run: |
        tar -czf cronometro-full.tar.gz --exclude=.git --exclude=.github .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cronometro-package
        path: cronometro-full.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Package for release
      run: |
        tar -czf cronometro-full.tar.gz --exclude=.git --exclude=.github .

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Build ${{ github.run_number }}
        files: cronometro-full.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
